### ISSUE TITLE
Getting configparser.NoSectionError: No section: 'User Data'

### ISSUE THREAD

**Issue by jreimone** [5agado/conversation-analyzer#1]
I tried to execute the scraper with Pthon 3.5.0 embedded 64bit for Windows 8 and got this error:

    Traceback (most recent call last):
      File "configparser.py", line 1136, in _unify_values
    KeyError: 'User Data'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "d:\MyPath\conversation-analyzer-master\src\util\conversationScraper.py", line 222, in <module>
        main(sys.argv[1:])
      File "d:\MyPath\conversation-analyzer-master\src\util\conversationScraper.py", line 215, in main
        cookie = config.get(DATA_SECTION, "Cookie")
      File "configparser.py", line 779, in get
      File "configparser.py", line 1139, in _unify_values
    configparser.NoSectionError: No section: 'User Data'

I entered the Cookie and the Fb_dtsg in the config.ini. Can you give me a pointer on how to resolve this?

**Comment by 5agado** [comment]
The problem seems to be related with your config.ini file.  The configparser doesn't find the 'User Data' section, the one where the Cookie and the Fb_dtsg parameters are. 
Check my config.ini file template, and also try to pass the complete filepath to another proper config.ini file via the --conf command.

**Comment by jreimone** [comment]
Thank you a lot. I could solve it by giving the path for the config file.
