### ISSUE TITLE
convert.py MemoryError

### ISSUE THREAD

**Issue by JakubKoralewski** [5agado/conversation-analyzer#15]
```bash
$ python convert.py --in F:\\projects\\fb_messages\\src-15mar2019\\facebook-username.zip --out xd
Traceback (most recent call last):
  File "convert.py", line 53, in <module>
    main(sys.argv[1:])
  File "convert.py", line 23, in main
    data = json.load(json_file)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
MemoryError
```

I'm assuming it's not the downloaded archive, but a single `message.json`?

**Comment by 5agado** [comment]
Yes, as described in the README you have to provide the single target message JSON.
