### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jreimone** [5agado/conversation-analyzer#3]
I could scrape the example conversation with myself. Then I wanted to parse it with this command:

python.exe ..\conversation-analyzer\src\util\conversationParser.py --in ..\scrapedChat\myUserID\conversation.pretty.json --out ..\scrapedChat\myUserID\parsedChat

But I get this error message:

      Traceback (most recent call last):
      File "..\conversation-analyzer\src\util\conversationParser.py", line 81, in <module>
        main(sys.argv[1:])
      File "..\conversation-analyzer\src\util\conversationParser.py", line 78, in main
        parseConversation(convPath, out, authors)
      File "..\conversation-analyzer\src\util\conversationParser.py", line 55, in parseConversation
        msg = parseMessage(action, authors)
      File "..\conversation-analyzer\src\util\conversationParser.py", line 22, in parseMessage
        if authorId not in authors:
    TypeError: argument of type 'NoneType' is not iterable

What to do here?

**Comment by 5agado** [comment]
I fixed the problem by simply setting the default value for the authors argument to be an empty dict.
