### ISSUE TITLE
A couple errors on running the app

### ISSUE THREAD

**Issue by flewid** [5agado/conversation-analyzer#7]
Hi, 

I'm trying to run this app to backup some conversations, however i get this error; 
```
`util ❯ python conversationScraper.py
Traceback (most recent call last):
  File "conversationScraper.py", line 2, in <module>
    import configparser
  File "/usr/local/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/backports/configparser/__init__.py", line 132, in <module>
    import io
  File "/Users/hugodrax/Documents/Source/conversation-analyzer/src/util/io.py", line 5, in <module>
    from pandas import read_csv
  File "/usr/local/lib/python2.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/usr/local/lib/python2.7/site-packages/pandas/compat/__init__.py", line 350, in <module>
    from dateutil import parser as _date_parser
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 37, in <module>
    from io import StringIO
ImportError: cannot import name StringIO`
```
so, then i simply do '**mv io.py io.py.bak**' and '**mv io.pyc io.pyc.bak**' and then it runs again, but now i get this error; 

```
`util ❯ python conversationScraper.py
Traceback (most recent call last):
  File "conversationScraper.py", line 12, in <module>
    from util import logger
ImportError: No module named util`
```

i am running python 2.7, and it returns this version

```
Python 2.7.12
```

**Comment by 5agado** [comment]
First wanted to point out that I used python 3.x for the code, so I am not sure how the code will behave with your python version. If you encounter more problems, you might want to try to install and run with a 3.x version.

For your second error, I apologize, my fault. You want to modify/correct this line to actually include the **util** folder.

    sys.path.append(dirname(__file__)+"\\..")  

Otherwise you might simply try to run the command from outside the **util** folder, in **src**.

I will shortly update the code with a fixed version.

**Comment by flewid** [comment]
Hey, thanks for the reply man! 

I didn't realize it was for python3, so, i'm doing this now; 

```
scraper@ubuntu:~/source/conversation-analyzer/src/util$ python3 conversationScraper.py
Traceback (most recent call last):
  File "conversationScraper.py", line 12, in <module>
    from util import logger
ImportError: No module named 'util'
scraper@ubuntu:~/source/conversation-analyzer/src/util$ cd ..
scraper@ubuntu:~/source/conversation-analyzer/src$ python3 ./util/conversationScraper.py
Traceback (most recent call last):
  File "./util/conversationScraper.py", line 12, in <module>
    from util import logger
ImportError: No module named 'util'
scraper@ubuntu:~/source/conversation-analyzer/src$

**Comment by flewid** [comment]
Okay, I have progressed much farther, by changing the include to 

`sys.path.append('/home/scraper/source/conversation-analyzer/src/')`

and, now i have the output 

```
scraper@ubuntu:~/source/conversation-analyzer/src/stats$ ls -lt
total 588
-rw-rw-r-- 1 scraper scraper  19541 Sep  1 22:27 wordsSaidJustByXXXXXXXXX.txt
-rw-rw-r-- 1 scraper scraper  21783 Sep  1 22:27 wordsSaidJustByXXXXXXXXX.txt
-rw-rw-r-- 1 scraper scraper 516431 Sep  1 22:27 wordcount.txt
```

so, i try and run 

```
scraper@ubuntu:~/source/conversation-analyzer/src/test$ python3 basicTests.py
Traceback (most recent call last):
  File "basicTests.py", line 11, in <module>
    from model.conversationDataframe import ConversationDataframe
ImportError: No module named 'model'
```

and


```
scraper@ubuntu:~/source/conversation-analyzer/src/test$ python3 testConvStats.py
Traceback (most recent call last):
  File "testConvStats.py", line 9, in <module>
    from model.conversationDataframe import ConversationDataframe
  File "/home/scraper/source/conversation-analyzer/src/model/conversationDataframe.py", line 11, in <module>
    from stats.convStatsDataframe import ConvStatsDataframe
ImportError: No module named 'stats.convStatsDataframe'; 'stats' is not a package
```

and

```
scraper@ubuntu:~/source/conversation-analyzer/src/test$ python3 testPlotting.py
Traceback (most recent call last):
  File "testPlotting.py", line 10, in <module>
    from model.conversationDataframe import ConversationDataframe
  File "/home/scraper/source/conversation-analyzer/src/model/conversationDataframe.py", line 11, in <module>
    from stats.convStatsDataframe import ConvStatsDataframe
ImportError: No module named 'stats.convStatsDataframe'; 'stats' is not a package
```

any ideas on what needs to change? I should have all modules installed now and most of the files seem to work, these are the two errors i get left between any of them when trying to run. 

thanks very much!

**Comment by flewid** [comment]
I think I have somewhat fixed it. I ended up having to rename the 'stats' directory to 'stats2' and then include stats2 in the files in question, and now I've got it generating statistics, as well as most of the tests working too.

**Comment by 5agado** [comment]
Hi @flewid ,
glad you manage to make it work, and sorry for the troubles. All the stats part was still a WIP, but I am planning of improving it, integrating your comments and most likely putting a ipython notebook to better and easily interface with stats and plotting.

**Comment by flewid** [comment]
oh that sounds great, I will let you know if i discover anything else :)
